font_family JetBrainsMono Nerd Font Mono
font_size 12

include tokyo_night_night.conf

shell fish
exe_search_path +/opt/homebrew/bin
exe_search_path +/home/linuxbrew/.linuxbrew/bin
shell_integration enabled

background_opacity 1.0
confirm_os_window_close 0
cursor_blink_interval 0
cursor_shape beam
disable_ligatures never
enable_audio_bell no
initial_window_height 40c
initial_window_width 145c
input_delay 3
macos_quit_when_last_window_closed yes
paste_actions quote-urls-at-prompt
remember_window_position yes
remember_window_size no
repaint_delay 10
scrollback_lines 10000
scrollbar always
strip_trailing_spaces smart
update_check_interval 0
window_padding_width 4

map ctrl+shift+down neighboring_window down
map ctrl+shift+left neighboring_window left
map ctrl+shift+right neighboring_window right
map ctrl+shift+up neighboring_window up

env LC_ALL=en_US.UTF-8
